
# Image output
/gate/output/projection/enable
/gate/output/projection/setFileName output/projection_sensi_APT1_{X}_{Y}_{Z}_{ANGLE}

/gate/output/projection/pixelSizeX 1 mm
/gate/output/projection/pixelSizeY 1 mm
/gate/output/projection/pixelNumberX 216
/gate/output/projection/pixelNumberY 216
/gate/output/projection/projectionPlane XY

/gate/output/root/enable

/gate/output/root/setFileName ./output/sensi_APT1_{X}_{Y}_{Z}_{ANGLE}

/gate/output/root/setRootHitFlag         1
/gate/output/root/setRootSinglesFlag      1
/gate/output/root/setRootNtupleFlag       0
