
# -------------------
# NanoSPECT/CT

# Default orientation is towards Z axis.
# According to CT image: need a rotation around X to start looking towards Y.

# Lengths: X is slightly larger than Y, like indicated on the collimator plane
# Width: arbitrary but must be larger than the larger collimator. Not too much to avoid intersection with phantom. 

# Crystal width varies between device. Here: XXXXX
# Crystal is NaI(Tl)


# -------------------



#SPECThead
/gate/world/daughters/name SPECThead
/gate/world/daughters/insert trpd
/gate/SPECThead/geometry/setX1Length 340 mm
/gate/SPECThead/geometry/setY1Length 340 mm
/gate/SPECThead/geometry/setX2Length 80 mm
/gate/SPECThead/geometry/setY2Length 84 mm
/gate/SPECThead/geometry/setZLength 192.5 mm  # 1+12+0.6+0.65+5  = 19.25 cm
/gate/SPECThead/geometry/disableCavity true
/gate/SPECThead/placement/setRotationAxis  0 1 0
/gate/SPECThead/placement/setRotationAngle -90 deg
/gate/SPECThead/placement/setTranslation  136.25 0 0 mm # 8/2+14.84/2
/gate/SPECThead/vis/setColor white
/gate/SPECThead/setMaterial Air
/gate/SPECThead/vis/forceWireframe


# Crystal
/gate/SPECThead/daughters/name crystal
/gate/SPECThead/daughters/insert box
/gate/crystal/geometry/setXLength 230 mm
/gate/crystal/geometry/setYLength 216 mm
/gate/crystal/geometry/setZLength 6.5 mm 
/gate/crystal/placement/setTranslation   0 0 -43 mm #(0.65-19.25)/2+5
/gate/crystal/setMaterial NaITl
/gate/crystal/vis/setColor yellow

/gate/systems/SPECThead/crystal/attach crystal
/gate/crystal/attachCrystalSD


# Shielding: Backside
# The back-side is fairly complex, and may have a strong influence on the
# spectrum: the model shown here is simplified
/gate/SPECThead/daughters/name shielding_backside_1
/gate/SPECThead/daughters/insert box
/gate/shielding_backside_1/geometry/setXLength 230 mm
/gate/shielding_backside_1/geometry/setYLength 216 mm
/gate/shielding_backside_1/geometry/setZLength  25 mm
/gate/shielding_backside_1/placement/setTranslation 0. 0. -58.75 mm #(2.5-19.25)/2+2.5
/gate/shielding_backside_1/setMaterial Al2O3  
/gate/shielding_backside_1/vis/setColor cyan
/gate/shielding_backside_1/vis/forceWireframe

/gate/SPECThead/daughters/name shielding_backside_2
/gate/SPECThead/daughters/insert box
/gate/shielding_backside_2/geometry/setXLength 230 mm
/gate/shielding_backside_2/geometry/setYLength 216 mm
/gate/shielding_backside_2/geometry/setZLength  25 mm
/gate/shielding_backside_2/placement/setTranslation 0. 0. -83.75 mm #(2.5-19.25)/2
/gate/shielding_backside_2/setMaterial Silicon 
/gate/shielding_backside_2/vis/setColor grey
/gate/shielding_backside_2/vis/forceWireframe

# Crystal shielding
/gate/SPECThead/daughters/name shield
/gate/SPECThead/daughters/insert box
/gate/shield/geometry/setXLength 230  mm 
/gate/shield/geometry/setYLength 216 mm
/gate/shield/geometry/setZLength 6 mm  
/gate/shield/placement/setTranslation  0 0 -36.85 mm #(0.6-19.25)/2+0.65+5
/gate/shield/setMaterial  Plastic
/gate/shield/vis/setColor green
/gate/shield/vis/forceWireframe

# Pyramid Pb
/gate/SPECThead/daughters/name pyramid_Pb
/gate/SPECThead/daughters/insert trpd
/gate/pyramid_Pb/geometry/setX1Length 253 mm
/gate/pyramid_Pb/geometry/setY1Length 253 mm
/gate/pyramid_Pb/geometry/setX2Length 80 mm
/gate/pyramid_Pb/geometry/setY2Length 84 mm
/gate/pyramid_Pb/geometry/setZLength 120 mm
/gate/pyramid_Pb/geometry/disableCavity true
/gate/pyramid_Pb/placement/setTranslation  0 0 26.25 mm #(19.25-1)/2-1./2-12./2 
/gate/pyramid_Pb/setMaterial LeadSb
/gate/pyramid_Pb/vis/setColor red
/gate/pyramid_Pb/vis/forceWireframe

# Pyramid Air
/gate/pyramid_Pb/daughters/name pyramid_Air
/gate/pyramid_Pb/daughters/insert trpd
/gate/pyramid_Air/geometry/setX1Length 230 mm 
/gate/pyramid_Air/geometry/setY1Length 215 mm 
/gate/pyramid_Air/geometry/setX2Length 76 mm
/gate/pyramid_Air/geometry/setY2Length 70 mm
/gate/pyramid_Air/geometry/setZLength 120 mm
/gate/pyramid_Air/geometry/disableCavity true
/gate/pyramid_Air/placement/setTranslation  0 0 0 mm
/gate/pyramid_Air/setMaterial Air
/gate/pyramid_Air/vis/setColor blue
/gate/pyramid_Air/vis/forceWireframe



# Collimator
/gate/SPECThead/daughters/name colli
/gate/SPECThead/daughters/insert pinhole_collimator

/gate/colli/geometry/setDimensionX1 80 mm
/gate/colli/geometry/setDimensionY1 84 mm
/gate/colli/geometry/setDimensionX2 80 mm
/gate/colli/geometry/setDimensionY2 84 mm
/gate/colli/geometry/setHeight 10 mm
/gate/colli/geometry/setRotRadius 45 mm
/gate/colli/geometry/input mac/APT2_hispect.pin

/gate/colli/placement/setTranslation  0 0 91.25 mm #  (19.25-1)/2 
/gate/colli/setMaterial Tungsten
/gate/colli/vis/setColor white
/gate/colli/vis/forceWireframe


# Repeater	
/gate/SPECThead/repeaters/insert ring
/gate/SPECThead/ring/setFirstAngle 0. deg
/gate/SPECThead/ring/setRepeatNumber 4
/gate/SPECThead/ring/setPoint1 0. 1. 0. mm 
/gate/SPECThead/ring/setPoint2 0. 0. 0. mm 




/gate/systems/SPECThead/describe
