/vis/open                             OGLIQt
/vis/drawVolume
/vis/viewer/flush
/vis/viewer/zoom 4.
/vis/viewer/set/viewpointThetaPhi 90 0
/tracking/storeTrajectory             1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction           accumulate

#/vis/scene/add/axes            0 0 0 20 mm
#/vis/scene/add/text            10 0 0 cm  20 0 0   X
#/vis/scene/add/text            0 10 0 cm  20 0 0   Y
#/vis/scene/add/text            0 0 10 cm  20 0 0   Z
/vis/viewer/set/auxiliaryEdge true
